import fs from 'fs'
import path from 'path'

// Configuration
const LOCAL_API = 'http://localhost:7071/api'
const LIVE_API = 'https://phonosium-api.azurewebsites.net/api'

// Quick helper to read .env file
function getEnvUrl() {
  try {
    const envPath = path.resolve(process.cwd(), '.env')
    if (fs.existsSync(envPath)) {
      const content = fs.readFileSync(envPath, 'utf8')
      const match = content.match(/^VITE_AZURE_FUNCTIONS_URL=(.+)$/m)
      if (match && match[1].trim()) {
        return match[1].trim()
      }
    }
  } catch (err) {
    // Ignore error
  }
  return null
}

async function runTest() {
  const args = process.argv.slice(2)
  const useLive = args.includes('--live')

  const envUrl = getEnvUrl()
  let apiBaseUrl = LOCAL_API

  if (useLive) {
    apiBaseUrl = LIVE_API
    console.log('Testing against LIVE deployed API...')
  } else if (envUrl) {
    apiBaseUrl = envUrl
    console.log(`Testing against API URL from .env: ${apiBaseUrl}`)
  } else {
    console.log(`Testing against LOCAL API (default): ${apiBaseUrl}`)
    console.log('  (Tip: Pass "--live" as an argument to test the live deployed API)')
  }

  const uploadUrlEndpoint = `${apiBaseUrl}/submissions/upload-url`
  console.log(`\nStep 1: Requesting SAS Upload URL from: ${uploadUrlEndpoint}`)

  const dummyFile = {
    fileName: 'test-upload-diagnostics.txt',
    fileType: 'text/plain',
    fileSize: 32,
    category: 'audio', // 'audio' or 'image' matches server containers
    submissionId: 'diagnostics-' + Math.random().toString(36).substring(2, 7)
  }

  let sasResponse
  try {
    const response = await fetch(uploadUrlEndpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(dummyFile)
    })

    if (!response.ok) {
      const text = await response.text()
      throw new Error(`HTTP ${response.status}: ${text || response.statusText}`)
    }

    sasResponse = await response.json()
    console.log('✅ Received SAS Token successfully!')
    console.log(`  - Blob Name: ${sasResponse.blobName}`)
    console.log(`  - SAS Upload URL: ${sasResponse.uploadUrl.substring(0, 120)}...`)
  } catch (error) {
    console.error('\n❌ Step 1 Failed: Could not get SAS Upload URL from API.')
    console.error(`Error details: ${error.message}`)
    console.log('\n🔍 Troubleshooting Tip for Step 1:')
    console.log('  - If testing LOCAL API: Make sure your local Azure Function is running on port 7071 (`cd api && npm run start`).')
    console.log('  - If testing LIVE API: Check if your Azure Function App is running and verify it doesn\'t return a 503 error.')
    console.log('  - Check that AZURE_STORAGE_CONNECTION_STRING is set correctly in your settings (Azure appsettings or local.settings.json).')
    process.exit(1)
  }

  console.log(`\nStep 2: Uploading dummy file to Azure Blob Storage...`)
  const dummyPayload = 'Phonosium E2E Upload Diagnostics Test File'

  try {
    const response = await fetch(sasResponse.uploadUrl, {
      method: 'PUT',
      headers: {
        'x-ms-blob-type': 'BlockBlob',
        'Content-Type': 'text/plain'
      },
      body: dummyPayload
    })

    if (!response.ok) {
      const text = await response.text()
      throw new Error(`HTTP ${response.status}: ${text || response.statusText}`)
    }

    console.log('✅ Step 2 Succeeded: File successfully uploaded to Azure Blob Storage!')
    console.log('\n🎉 End-to-end upload pipeline is 100% functional!')
  } catch (error) {
    console.error('\n❌ Step 2 Failed: Could not upload file to Azure Blob Storage.')
    console.error(`Error details: ${error.message}`)
    console.log('\n🔍 Troubleshooting Tips for Step 2 (Blob Upload Failure):')

    if (error.message.includes('SignatureFieldsInvalid') || error.message.includes('AuthenticationFailed')) {
      console.log('  👉 AUTHENTICATION FAILURE: The SAS token generated by the Function App is invalid.')
      console.log('     - Verify that the system time on your machine is in sync with internet time. SAS tokens rely on precise timestamps.')
      console.log('     - Double check your AZURE_STORAGE_ACCOUNT_KEY in settings. If the key is invalid, generated signatures will fail authentication.')
    } else if (error.message.includes('ContainerNotFound')) {
      console.log('  👉 CONTAINER MISSING: The container "submissions-audio" does not exist in your Storage Account.')
      console.log('     - Your Function App should auto-create it, or you can create it manually in the Azure Portal.')
    } else if (error.message.includes('Failed to fetch') || error.message.includes('TypeError')) {
      console.log('  👉 CORS or NETWORK BLOCK:')
      console.log('     - If running in a browser, this is almost certainly blocked by the Storage Account\'s CORS policy.')
      console.log('     - You MUST add a CORS rule to your Azure Storage Account for your origins (e.g., http://localhost:5173, http://localhost:5174).')
      console.log('     - Run this Azure CLI command in your terminal to automatically set it up:')
      console.log('\n       az storage cors add --services b --origins "http://localhost:5173" "http://localhost:5174" --methods PUT OPTIONS --allowed-headers "*" --exposed-headers "*" --account-name phonosium')
    } else {
      console.log('     - Check your storage account configuration and container access level settings.')
    }
    process.exit(1)
  }
}

runTest()
